### PR TITLE
Fixes #214

### LINKED ISSUE #214: Hover info not working for non-local functions
Hover over function name should show help for standard functions and function heads for project functions. It used to work but in 0.7.8 it works only for functions without module - so only for local functions or BIFs. Hovering over a function like lists:member shows nothing.

### PR DESCRIPTION
**Pull request by wojteksurowka**
Some fixes:
Autocomplete works with CRLF line endings
[#214](https://github.com/pgourlain/vscode_erlang/issues/214) Hover info not working for non-local functions
[#137](https://github.com/pgourlain/vscode_erlang/issues/137) [IntelliSense] "of" + Enter = "offset"?!

### CODE REVIEW

File: apps/erlangbridge/src/lsp_handlers.erl [hunk 1]
```diff
@@ -291,14 +291,17 @@ severity(_) -> 1.
 
 auto_complete(File, Line, Text) ->
     RegexList = [
-        {"[^a-zA-Z0-9_@]([a-z][a-zA-Z0-9_@]*):((?:[a-z][a-zA-Z0-9_@]*)?)$", module_function},
-        {"#((?:[a-z][a-zA-Z0-9_@]*)?)$", record},
-        {"#([a-z][a-zA-Z0-9_@]*)\.((?:[a-z][a-zA-Z0-9_@]*)?)$", field},
-        {"[^a-zA-Z0-9_@]([A-Z][a-zA-Z0-9_@]*)$", variable},
-        {"^-([a-z]*)$", attribute},
-        {"([a-z][a-zA-Z0-9_@]*)$", atom}
+        {"[^a-zA-Z0-9_@](case)[^a-zA-Z0-9_@].*of\r?$", case_of},
```
Comment (Yozhig) [inline apps/erlangbridge/src/lsp_handlers.erl:294]: I've tested 'case of' autocompletion cancelation, and it does not work for me in most cases. It triggers on 'o' letter most of the time. So i suggest to modify regexp as follows:
```suggestion
        {"[^a-zA-Z0-9_@](case)[^a-zA-Z0-9_@].*\sof?\r?$", case_of},
```
It will cause more false positives but i think we can deal with it.

Comment (wojteksurowka) [reply apps/erlangbridge/src/lsp_handlers.erl]: Agreed, thank you!
